language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm
    - nightly

matrix:
    allow_failures:
        - nightly

before_script:
    - composer install

before_script:
    - composer install --no-interaction
    - mkdir -p build/logs
    - composer fix-syntax

script:
    - vendor/bin/phpunit --coverage-text
